### ISSUE TITLE
[Bug] Doesn't work if there's a space in the image filename

### ISSUE THREAD

**Issue by scambier** [mattjennings/mdsvex-relative-images#5]
Title says it all :)

Works:
```md
![](./some-image.png)
```

Doesn't work:
```
![](./some image.png)
```

Maybe the cause of #4 too?

**Comment by mattjennings** [comment]
Ah, good catch. I think we would need to just replace spaces with underscores here:

https://github.com/mattjennings/mdsvex-relative-images/blob/54aa71cd31b94122bf4b800fef90d84c58bf5bb9/index.js#L19

**Comment by mattjennings** [comment]
Should work in 1.0.3. Because spaces are not valid URL characters, you will have to encode them as `%20`. i.e

```
![](./some%20image.png)
```
